server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bishe?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
mybatis:
  mapper-locations: classpath*:mapper/*.xml
